### ISSUE TITLE
Viewer seems broken on macOS (arm)

### ISSUE THREAD

**Issue by thoellt** [ManiVaultStudio/ImageViewerPlugin#109]
See image. Everything built from scratch. Steps: Open image -> right click -> view -> Image Viewer

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/2159209/224370118-1bdc5a0f-28f2-4edd-886f-a33b9f2f8158.png">

**Comment by alxvth** [comment]
Does #113 solve this?

**Comment by ThomasKroes** [comment]
I am not 100% sure. With the sun dataset, everything seems to work okay on Mac OS. I don't know if this dataset was also tested on Windows, but if it does not work there it might also be a problem with the image loader plugin.

**Comment by thoellt** [comment]
Yes, seems fixed in the latest version!
