### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by ThomasKroes** [ManiVaultStudio/ImageViewerPlugin#114]
The OpenGL window is not always refreshed.

Steps to reproduce:

1. Drag and drop an image dataset
2. The view is not updated
3. Click in the view to trigger a render

**Comment by thoellt** [comment]
I noticed a probably related issue today related to color map (ranges?).

Steps:
1. visualize an image dataset using the image viewer
1. calculate a t-SNE on the image dataset and visualize it in a scatterplot with coordinates as color using a 2D colormap
1. drag and drop the t-SNE embedding dataset onto the existing image viewer.

The resulting image will now show the t-SNE coordinates, automatically switching to a 2D coloring mode and 2D colormap (nice!), but the ranges seem off (possibly it also does not use the second dimension of the 2D colormap).

4. switching the channels to be visualized to different  channels (e.g., dim1 = y and dim2 = x) and back to the original setting will show the correct (but clearly different from the initial state) colors.

**Comment by ThomasKroes** [comment]
You are correct, I have noticed this incorrect behavior too. This is indeed related. I will take a look asap!

**Comment by ThomasKroes** [comment]
The problem with the 2D color map is solved now. The issue with the refresh of the OpenGL window is related to the pixel selection tool of the core, see https://github.com/ManiVaultStudio/core/pull/443
